### ISSUE TITLE
refactor: remove cases of prop drilling

### ISSUE THREAD

**Issue by idax6797** [RUC-MSc-CS-CIT-2024/portfolio_subproject_3#121]
We are using prop drilling in the `MediaGrid` `MediaCard` for loading, we should go through the components and ensure that we dont do this other places. And also fix the cases that exists

**Comment by idax6797** [comment]
Yup, I will have a look at this, but maybe we should rethink this, @sofushn @JuliusKryger @MarLaslo, because do we like the placeholder stuff, and this is used to show that, so if no then the loading state will be removed.

**Comment by sofushn** [comment]
I feel like there are two solutions, either introduce a context (`ApiContext` or something like that) or let it be and argue that it was needed for the purpose of showing placeholders if its brought up at the exam

**Comment by sofushn** [comment]
Alternatively we could look into inferring loading from some of the other properties, this is properly the most elegant solution but I haven't looked at the implementation in detail so I don't know if its possible
